#version 450 core

#define FACES  5

layout(local_size_x = FACES) in;
layout(std430, binding = 0) buffer ssbo {
	uint row[];
};
layout(r32ui, binding = 1) uniform uimage2DArray hemicube;

uniform float width;

uint getFaceId(ivec2 coord, uint face){
	return imageLoad(hemicube, ivec3(coord, face)).r;
}

void main() {
	ivec2 coords = ivec2(gl_WorkGroupID.xy);
	uint face = getFaceId(coords,gl_LocalInvocationID.x);
	atomicAdd(row[face],1u);
}